### ISSUE TITLE
 'module' object has no attribute 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by edsu** [edsu/pymarc#87]
**an [email](https://groups.google.com/forum/#!topic/pymarc/iEUvHQmbghc) from hf36@nyu.edu** 

I've just started to work with python/pymarc on a new computer and used pip to install pymarc (using Python 2.7.10), but when I've just tried to run a python script, I get the following error for the "import pymarc" line:

```
172-16-245-249:bin hf36$ python aco-1-xml2mrc-oclc-nums.py

Traceback (most recent call last):

  File "aco-1-xml2mrc-oclc-nums.py", line 9, in <module>

    import pymarc

  File "/Library/Python/2.7/site-packages/pymarc/__init__.py", line 62, in <module>

    from .record import *

  File "/Library/Python/2.7/site-packages/pymarc/record.py", line 31, in <module>

    @six.python_2_unicode_compatible

AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

I assume I've something out of date or such, but have no idea how to troubleshoot this error... (I'm not that versed in installation issues)

**Comment by Wooble** [comment]
Can you do the following:

```
import six
print(six.__version__)
```

(I *think* that should be in any version of six you'd get installed, though... You don't have a random file named "six.py" lying around, do you?)

**Comment by Wooble** [comment]
(This was a problem with the setup.py not specifying a minimum version of `six`, and was fixed in version 3.1.2)

**Comment by deepPython** [comment]
I am facing the same issue while running django server. I am not using virtual environment. Also, six package is  on latest version in python. But  still getting the error, What am I doing wrong?

pip show six
---
Name: six
Version: 1.10.0
Location: /usr/local/lib/python2.7/dist-packages
Requires:
---
$python ~/django/mysite/manage.py runserver localhost
[1] 3913
$ AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
